### PR TITLE
ENV: Remove duplicate settings

### PR DESCRIPTION
**Pull request by GaryJones**
`WP_ACCESSIBLE_HOSTS` and `WP_HTTP_BLOCK_EXTERNAL` appeared under the Security and Proxy headings.

### CODE REVIEW

**Comment by Giuseppe-Mazzapica** [comment]
@GaryJones can you please send PR to `dev` branch? I updated readme adding contributions informations. Thanks a lot.

**Comment by GaryJones** [comment]
If you change the HEAD branch (default branch in GitHub repo settings), then PRs will automatically go to the right branch.

**Comment by franz-josef-kaiser** [comment]
@GaryJones Done. 

@Giuseppe-Mazzapica FYI I also added the `master` branch as "protected" branch to prevent force pushes as well as it getting deleted.

**Comment by GaryJones** [comment]
Closing in favour of #17.

**Pull request closed without merging**
