### PR TITLE
Class refection response added to MuLoader

### PR DESCRIPTION
**Pull request by EkAndreas**
When using reflection plugins as Query Monitor this class responds with a name as string.

### CODE REVIEW

**Comment by Giuseppe-Mazzapica** [comment]
Can you please change

```php
return 'WCM\WPStarter\MuLoader';
```

to 

```php
return __CLASS__;
```

**Comment by EkAndreas** [comment]
Yes! Correct!

**Comment by Giuseppe-Mazzapica** [comment]
Fine. I'll merge in 2.1

**Comment by EkAndreas** [comment]
Ok, thanks!

**Comment by Giuseppe-Mazzapica** [comment]
Thanks to you for your interest and your contribute.

**Comment by EkAndreas** [comment]
Oh, its a great lib you guys have created. Hope I will get a blog post about converting my old and large WP-project with the wpstarter-base. Easy pancake, but still I have the deployment push to do first :-)

**Comment by Giuseppe-Mazzapica** [comment]
Thanks @EkAndreas

ping me if you write that post!

PS the problem with Query Monitor is a [QM issue](https://github.com/johnbillion/query-monitor/pull/120), I hope they will merge my PR.

**Comment by Giuseppe-Mazzapica** [comment]
Going to close this, because with [Query Monitor 2.7.4](https://github.com/johnbillion/query-monitor/releases/tag/2.7.4) the issue I reported that caused problems with WP Starter has been fixed (thanks @johnbillion) so there is no need to add `__toString()` method now and we can reserve it for future use.

Thanks @EkAndreas anyway and any feedback on WP Starter that will be appreciated.

**Pull request closed without merging**
