### PR TITLE
Change Log

### PR DESCRIPTION
**Pull request by GaryJones**
Points taken from the existing release notes. Could probably be improved further with other props / issue/pr links, but it should be sufficient for most.

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
Why do we need a changelog as separate file? We already have the [Release list](https://github.com/wecodemore/wpstarter/releases). I would just link there. _Note: I fixed them last week, removing and adding was needed. Still can be improved further by using "added/removed/fixed" headlines for each._

**Comment by GaryJones** [comment]
Because it's standard, and git-platform agnostic (the changelog gets delivered with the rest of the files). If this repo moves to Bitbucket, or a Satis install, the list of changes (and not just the list of commits) are kept with it.

For each release, just populate the changelog, and the copy over to the GitHub releases if you wish.

**Comment by GaryJones** [comment]
> Still can be improved further by using "added/removed/fixed" headlines for each.

The http://keepachangelog.com format suggests 6 subheadings, though for such small number of bullet points per release (which is good in itself), I see the subheadings as redundant noise, especially when the subsections are empty.

**Comment by franz-josef-kaiser** [comment]
Agree. But as maintaining this is neither funny not makes contributing easier (we would need to force people to add to those changelog or do it ourselfs), I would suggest to automate this on _Circle CI_ or on _Travis CI_: Fetch the release list with the [GitHub API](https://developer.github.com/v3/repos/releases/), loop over it and append to a `changelog.md` to extend the PR. How does that sound?

**Comment by GaryJones** [comment]
That sounds like even more hard-work and a another chance for things to potentially break :-)

I don't agree that contributors should be amending the change log - it's another potential source of merge conflict, and the wording may not reflect how the repo maintainer wants to communicate a change. 

For this repo, with so few changes per release, it can either be done at release time (as you would with the release notes anyway) and just scrap the Unreleased section, or whenever a merge or direct commit is made, just add the entry to the change log when the subject is fresh in your mind, and the issue / PR ticket number is doesn't have to be found again. At release time, you can then just add the date and linked version number to the top, and a new Unreleased above that - it's not that much work. Making release notes is easy, and you've then already done it :-)

**Comment by Giuseppe-Mazzapica** [comment]
Change log in a separate file is good for me: it's easy to access it while developing, in fact looking a single file in IDE context is easier to go GitHub and look for release list.

http://keepachangelog.com/ suggests 6 subheadings, but not all of them are mandatory.

In the example given in the website only subheadings which have entries are included.
In release notes I usually at least include `Added`, `Changed`, `Fixed` because that works for me as a checklist if I should release a patch, a minor or a major release, because of Semver. For example if I have something in `Added` that is a minor release, if I have some BC changes in `Changed` that is major release.

In theory, I would just copy and paste from release notes into Changelog file. But since I was always too lazy to do that, I merged @GaryJones PR becasuse some Changelog is better than nothing. And the one he sent was pretty good anyway.

Maybe later, WP Starter changelog could be made more in line with release notes and 
http://keepachangelog.com/.

**Pull request merged**
